name: CI

on:
  push:
    branches: [ main, revision ]
  pull_request:
    branches: [ main, revision ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install ruff pytest
      - name: Ruff lint
        run: ruff check .

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install ruff pytest
      - name: Run tests
        run: pytest -q
